variables:
  - group: terraform-base
  - group: devops-base
  - group: devops-non-prod
  - group: devops-dev

pool:
  vmImage: ubuntu-22.04

trigger:
  batch: true
  branches:
    include:
      - master
      - main
  paths:
    exclude:
      - chef/**/*
      - pipelines/cluster_config.yml

stages:
  - template: ./templates/plan.yml
    parameters:
      sa:                 $(sa)
      container:          $(container)
      service_connection: $(service_connection)
      environment:        $(environment)
      project:            $(project)
      subscription_id:    $(subscription_id)
      id_file:            id_rsa.pub

  - template: ./templates/apply.yml
    parameters:
      sa:                 $(sa)
      container:          $(container)
      service_connection: $(service_connection)
      environment:        $(environment)
      project:            $(project)
      subscription_id:    $(subscription_id)
      id_file:            id_rsa.pub
