name 'aks'
maintainer 'Leif Eriksen'
maintainer_email 'leif.eriksen.au+aks@gmail.com'
license 'All Rights Reserved'
description 'Installs/Configures aks prerequisites'
version '0.0.1'
chef_version '>= 16.0'
source_url 'https://github.com/leriksen/showtech'
issues_url 'https://github.com/leriksen/showtech/issues'
